export const getPostProcess = (categoryname) => {
  const postProcessData = {
    aluminiumdiecasting: [
      { id: 1, name: "Deburring" },
      { id: 2, name: "Sandblasting" },
      { id: 3, name: "Anodizing" },
      { id: 4, name: "Powder coating" },
      { id: 5, name: "CNC machining" },
      { id: 6, name: "Electroplating" },
      { id: 7, name: "Painting" },
      { id: 8, name: "Printing" },
    ],
    sandcasting: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Heat treatment" },
      { id: 3, name: "Impregnation" },
      { id: 4, name: "Conventional machining" },
      { id: 5, name: "CNC machining" },
      { id: 6, name: "Electroplating" },
      { id: 7, name: "Chemical coating" },
      { id: 8, name: "Powder coating" },
      { id: 9, name: "Painting" },
    ],
    investmentcasting: [
      { id: 1, name: "SS Shot Blasting" },
      { id: 2, name: "Heat treatment" },
      { id: 3, name: "Pickle & Passivate" },
      { id: 4, name: "Electropolishing" },
      { id: 5, name: "Electroplating" },
      { id: 6, name: "Chemical coating" },
    ],
    opendieforging: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Conventional machining" },
      { id: 3, name: "CNC machining" },
      { id: 4, name: "Grinding" },
      { id: 5, name: "Powder coating" },
      { id: 6, name: "Phosphate coating" },
      { id: 7, name: "Painting" },
      { id: 8, name: "Anodizing" },
      { id: 9, name: "Electroplating" },
      { id: 10, name: "Electropolishing" },
      { id: 11, name: "Polishing (Lapping & Honing)" },
    ],
    closeddieforging: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Conventional machining" },
      { id: 3, name: "CNC machining" },
      { id: 4, name: "Grinding" },
      { id: 5, name: "Powder coating" },
      { id: 6, name: "Phosphate coating" },
      { id: 7, name: "Painting" },
      { id: 8, name: "Anodizing" },
      { id: 9, name: "Electroplating" },
      { id: 10, name: "Electropolishing" },
      { id: 11, name: "Polishing (Lapping & Honing)" },
    ],
    cncmachining: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Grinding" },
      { id: 3, name: "Powder coating" },
      { id: 4, name: "Phosphate coating" },
      { id: 5, name: "Painting" },
      { id: 6, name: "Anodizing" },
      { id: 7, name: "Electroplating" },
      { id: 8, name: "Electropolishing" },
      { id: 9, name: "Polishing (Lapping & Honing)" },
    ],
    conventionalmachining: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Grinding" },
      { id: 3, name: "Powder coating" },
      { id: 4, name: "Phosphate coating" },
      { id: 5, name: "Painting" },
      { id: 6, name: "Anodizing" },
      { id: 7, name: "Electroplating" },
      { id: 8, name: "Electropolishing" },
      { id: 9, name: "Polishing (Lapping & Honing)" },
    ],
    equipmentfabrication: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Machining" },
      { id: 3, name: "Grinding" },
      { id: 4, name: "Painting" },
      { id: 5, name: "Powder coating" },
      { id: 6, name: "Galvanization" },
      { id: 7, name: "Phosphate coating" },
    ],
    sheetmetalfabrication: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Machining" },
      { id: 3, name: "Grinding" },
      { id: 4, name: "Painting" },
      { id: 5, name: "Powder coating" },
      { id: 6, name: "Galvanization" },
      { id: 7, name: "Phosphate coating" },
    ],
    structuralfabrication: [
      { id: 1, name: "Abrasive blasting" },
      { id: 2, name: "Machining" },
      { id: 3, name: "Grinding" },
      { id: 4, name: "Painting" },
      { id: 5, name: "Powder coating" },
      { id: 6, name: "Galvanization" },
      { id: 7, name: "Phosphate coating" },
    ],
    aluminiumextrusion: [
      { id: 1, name: "Deburring" },
      { id: 2, name: "Sandblasting" },
      { id: 3, name: "Anodizing" },
      { id: 4, name: "Electroplating" },
      { id: 5, name: "Painting" },
      { id: 6, name: "Printing" },
      { id: 7, name: "Powder Coating" },
      { id: 8, name: "PVDF Coating" },
      { id: 9, name: "Bright Dipping" },
    ],
    plasticmolding: [
      { id: 1, name: "Trimming" },
      { id: 2, name: "Painting" },
      { id: 3, name: "Coating" },
      { id: 4, name: "Printing" },
      { id: 5, name: "Labelling" },
      { id: 6, name: "Assembly" },
    ],
    injectionmolding: [
      { id: 1, name: "Trimming" },
      { id: 2, name: "Painting" },
      { id: 3, name: "Coating" },
      { id: 4, name: "Printing" },
      { id: 5, name: "Labelling" },
      { id: 6, name: "Assembly" },
    ],
  };

  return postProcessData[categoryname] || [];
};
