export const TNA_STAGES = {
  SAMPLE_APPROVAL: 'SAMPLE_APPROVAL',
  PROCUREMENT: 'PROCUREMENT',
  PRODUCTION_AND_APPROVAL: 'PRODUCTION_AND_APPROVAL',
  LOGISTICS: 'LOGISTICS',
  ALL: 'ALL',
};

export const TNA_STATUS = {
  DRAFT: 'DRAFT',
  APPROVAL_PENDING_MJADMIN: 'APPROVAL_PENDING_MJADMIN',
  ACCEPTANCE_PENDING_FROM_BUYER: 'ACCEPTANCE_PENDING_FROM_BUYER',
  UNDER_DISCUSSION: 'UNDER_DISCUSSION',
  ACCEPTED_BY_BUYER: 'ACCEPTED_BY_BUYER',
  UNDER_EXECUTION: 'UNDER_EXECUTION',
  DELIVERED: 'DELIVERED',
};

export const MILESTONE_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  UNDER_EXECUTION: 'UNDER_EXECUTION',
  APPROVAL_PENDING_MJADMIN: 'APPROVAL_PENDING_MJADMIN',
  ACCEPTANCE_PENDING_FROM_BUYER: 'ACCEPTANCE_PENDING_FROM_BUYER',
  COMPLETED: 'COMPLETED',
  APPROVED: 'APPROVED',
  DELAYED: 'DELAYED',
  UNDER_REVISION: 'UNDER_REVISION',
  IN_PROGRESS: 'IN_PROGRESS',
};
